image: Visual Studio 2015
configuration: Debug
platform: Any CPU
before_build:
- nuget restore

build:
    verbosity: detailed
    project: Project_Silicon.sln
 
after_build:
- cmd: tree /F
- cmd: 7z a -tzip "Project Ports/bin/Debug/Project-Silicon.zip" "Project Ports/bin/Debug/*"

artifacts:
- path: Project Ports/bin/Debug/BSODPrank.zip
  name: DevBuild

deploy:
    provider: GitHub
    release: Continuous build
    description: 'Project Silicon Development Builds'
    auth_token:
        secure: MeuJU9DaBpnzRdWaqvDfR4M7WhtB90FIpmYkZ5GmS8GyVSWyHT2FAMtDczW3D/JQ
    artifact: /.*\.zip/
    draft: false
    prerelease: true
    force_update: true
    tag: continuous
    on:
        appveyor_repo_tag: true