artifacts:
  - path: Project-Ports\bin\debug\* 
    name: Project Ports
after_build:
  - ps: $root = Resolve-Path .\Project-Ports\bin\debug; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName test101 }
