artifacts:
  - path: Ports-%APPVEYOR_REPO_COMMIT%.zip
    name: Ports-%APPVEYOR_REPO_COMMIT%
    
after_build:
# scripts to run after build
- netstat -ab
- tree /F
# zip the archive
- '7z a Ports-%APPVEYOR_REPO_COMMIT%.zip bin/Debug'
